services:  
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=produto_db
    ports:
      - "3306:3306"
    volumes:
      - db-data-1:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s
  server:
    build:
      context: .
      target: final
    ports:
      - 5025:8080
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=produto_db;User=root;Password=root;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db-data-1:
